image: kaiwinter/docker-java8-maven


cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

stages:
  - build
  - test
  - package

maven-build:
  script:
    - "mvn --flink clean compile -B"
  stage: build

maven-test:
  script:
    - "mvn --flink test -B"
    - "cat */target/site/jacoco/index.html"
  stage: test

test-coverage:
  script:
    - "mvn --flink test -B"
    - for file in */target/site/jacoco/index.html; do test `cat $file | perl -pe 's|^.*Total.*?([0-9]+)%.*|\1|'` -gt 10 || exit 1; done
  stage: test
  only:
    - master

checkstyle:
  script:
    - "mvn --flink compile checkstyle:check -B"
  stage: test

findbugs:
  script:
    - "mvn --flink compile findbugs:check -B"
  stage: test

pmd:
  script:
    - "mvn --flink pmd:check -B"
  stage: test

maven-package:
  script:
    - "mvn --flink package -B"
  stage: package
#  only:
#    - master
